/* =========================================================
   NOGUEIRA CASA — DEMO
   products.js — dados do catálogo (fictício, para demonstração)
========================================================= */

const PRODUCTS = [
  {
    id: "sofa-milano",
    name: "Sofá Milano Retrátil e Reclinável",
    category: "Sofás",
    price: 3499,
    shortDesc: "3 lugares em suede, com assento retrátil e encosto reclinável.",
    description:
      "O Sofá Milano combina conforto e praticidade em um único móvel. Com sistema retrátil e reclinável independente em cada lado, ele se adapta ao momento de assistir um filme, receber visitas ou simplesmente relaxar depois de um dia cheio.",
    features: [
      "Assento retrátil e encosto reclinável independentes",
      "Espuma D33 de alta resistência",
      "Pés em madeira maciça com acabamento amendoado",
      "Percintas elásticas para maior durabilidade",
    ],
    dimensions: "2,02m (L) x 0,95m (P) x 0,88m (A)",
    materials: "Estrutura em madeira de reflorestamento, revestimento em suede",
    options: ["Cinza grafite", "Bege areia", "Verde musgo"],
    image: "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&q=80&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "sofa-copenhague",
    name: "Sofá Copenhague Modular de Canto",
    category: "Sofás",
    price: 4290,
    shortDesc: "Módulo de canto com chaise, ideal para salas amplas.",
    description:
      "Inspirado no design escandinavo, o Copenhague une linhas retas e conforto profundo. O módulo de canto com chaise cria um espaço de estar generoso, perfeito para famílias ou para quem gosta de receber.",
    features: [
      "Chaise reversível (pode ser montado à esquerda ou à direita)",
      "Almofadas de encosto soltas em fibra siliconada",
      "Estrutura interna em madeira multilaminada",
      "Tecido com tratamento antimanchas",
    ],
    dimensions: "2,80m (L) x 1,70m (P) x 0,82m (A)",
    materials: "Estrutura em madeira multilaminada, revestimento em linho sintético",
    options: ["Cinza claro", "Off-white"],
    image: "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&q=80&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "cama-toscana",
    name: "Cama Box Casal Toscana",
    category: "Camas",
    price: 2190,
    shortDesc: "Cabeceira estofada capitonê e base box com pés palito.",
    description:
      "A Cama Toscana traz elegância ao quarto com sua cabeceira estofada em capitonê, um clássico que nunca sai de moda. O conjunto já acompanha a base box, pronta para receber o colchão.",
    features: [
      "Cabeceira capitonê com botões forrados",
      "Base box com suporte reforçado",
      "Pés palito em madeira com acabamento fosco",
      "Altura pensada para facilitar a arrumação da cama",
    ],
    dimensions: "1,58m (L) x 1,98m (C) x 1,20m (A da cabeceira)",
    materials: "Cabeceira em MDF revestido de tecido suede, base em madeira",
    options: ["Cinza", "Rosé", "Azul petróleo"],
    image: "https://cdn.pixabay.com/photo/2018/01/23/06/58/modern-minimalist-bedroom-3100786_1280.jpg",
    featured: true,
  },
  {
    id: "cama-nord",
    name: "Cama Solteiro Nord com Painel",
    category: "Camas",
    price: 1190,
    shortDesc: "Estrutura minimalista com painel embutido para apoio.",
    description:
      "Pensada para quartos de crianças, adolescentes ou quartos de hóspedes, a Cama Nord tem um desenho limpo e um painel integrado que funciona como apoio para travesseiros e decoração.",
    features: [
      "Painel embutido na cabeceira",
      "Estrado em madeira com ripas flexíveis",
      "Acabamento fosco resistente a riscos",
      "Design compacto para quartos menores",
    ],
    dimensions: "0,96m (L) x 2,03m (C) x 0,90m (A do painel)",
    materials: "MDP com acabamento em laminado melamínico",
    options: ["Branco", "Carvalho natural"],
    image: "https://cdn.pixabay.com/photo/2016/03/28/09/34/bedroom-1285156_640.jpg",
  },
  {
    id: "guarda-roupa-venezza",
    name: "Guarda-roupa Venezza 6 Portas",
    category: "Guarda-roupas",
    price: 2890,
    shortDesc: "Amplo espaço interno com cabideiro duplo e gavetas.",
    description:
      "O Venezza foi criado para quem precisa de organização de verdade. São seis portas, cabideiro duplo, prateleiras internas e um conjunto de gavetas para roupas dobradas, tudo em um design elegante.",
    features: [
      "6 portas com dobradiças de fechamento suave",
      "Cabideiro duplo + prateleiras ajustáveis",
      "4 gavetas internas com corrediças metálicas",
      "Puxadores em perfil embutido",
    ],
    dimensions: "2,50m (L) x 0,60m (P) x 2,10m (A)",
    materials: "MDF com acabamento em laminado texturizado",
    options: ["Nogueira", "Branco fosco"],
    image: "https://images.unsplash.com/photo-1718939045285-b67f9e9f9f8b?w=1200&q=80&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "guarda-roupa-firenze",
    name: "Guarda-roupa Casal Firenze com Espelho",
    category: "Guarda-roupas",
    price: 2190,
    shortDesc: "3 portas, sendo uma com espelho de corpo inteiro.",
    description:
      "O Firenze une funcionalidade e praticidade: uma das portas conta com espelho de corpo inteiro, ideal para quartos de casal que precisam de um espaço a mais para se arrumar sem ocupar área extra.",
    features: [
      "Porta central com espelho de corpo inteiro",
      "Cabideiro simples + duas prateleiras superiores",
      "3 gavetas espaçosas",
      "Estrutura reforçada nas laterais",
    ],
    dimensions: "1,80m (L) x 0,55m (P) x 2,05m (A)",
    materials: "MDF com espelho laminado de segurança",
    options: ["Carvalho", "Branco"],
    image: "https://images.unsplash.com/photo-1718939045285-b67f9e9f9f8b?w=1200&q=80&auto=format&fit=crop",
  },
  {
    id: "mesa-carvalho",
    name: "Mesa de Jantar Carvalho 6 Lugares",
    category: "Mesas",
    price: 1990,
    shortDesc: "Tampo em madeira maciça com pés em ferro preto.",
    description:
      "Uma mesa feita para reunir a família. O tampo em madeira maciça traz aconchego, enquanto os pés em ferro preto fosco dão um toque industrial contemporâneo ao ambiente.",
    features: [
      "Tampo em madeira maciça de reflorestamento",
      "Pés em ferro com pintura eletrostática",
      "Acabamento verniz fosco resistente a manchas",
      "Acompanha 6 lugares confortáveis",
    ],
    dimensions: "1,80m (C) x 0,90m (L) x 0,76m (A)",
    materials: "Madeira maciça e estrutura em ferro",
    options: ["Natural", "Imbuia"],
    image: "https://images.unsplash.com/photo-1676223303556-bef6fdac9331?w=1200&q=80&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "mesa-ares",
    name: "Mesa de Centro Ares",
    category: "Mesas",
    price: 690,
    shortDesc: "Design redondo com tampo em vidro e base em madeira.",
    description:
      "Leve e versátil, a Mesa Ares combina um tampo redondo em vidro temperado com uma base torneada em madeira maciça, trazendo sofisticação para qualquer composição de sala.",
    features: [
      "Tampo em vidro temperado de 8mm",
      "Base em madeira maciça torneada",
      "Bordas arredondadas e polidas",
      "Fácil de higienizar",
    ],
    dimensions: "0,80m (Ø) x 0,42m (A)",
    materials: "Vidro temperado e madeira maciça",
    options: ["Natural"],
    image: "https://images.unsplash.com/photo-1676223303556-bef6fdac9331?w=1200&q=80&auto=format&fit=crop",
  },
  {
    id: "cadeira-bristol",
    name: "Cadeira Estofada Bristol",
    category: "Cadeiras",
    price: 449,
    shortDesc: "Estofado em veludo com base em madeira palito.",
    description:
      "A Bristol traz um toque de sofisticação para a mesa de jantar ou como cadeira avulsa de composição. O estofado em veludo e a base em madeira palito formam uma combinação elegante e atemporal.",
    features: [
      "Estofado em veludo de fácil limpeza",
      "Espuma injetada de alta densidade",
      "Base em madeira maciça palito",
      "Estrutura interna reforçada",
    ],
    dimensions: "0,52m (L) x 0,55m (P) x 0,84m (A)",
    materials: "Madeira maciça e tecido veludo",
    options: ["Verde esmeralda", "Terracota", "Cinza"],
    image: "https://images.unsplash.com/photo-1676223303556-bef6fdac9331?w=1200&q=80&auto=format&fit=crop",
  },
  {
    id: "cadeira-ergomax",
    name: "Cadeira de Escritório ErgoMax",
    category: "Cadeiras",
    price: 899,
    shortDesc: "Apoio lombar ajustável e braços reguláveis.",
    description:
      "Para quem passa horas trabalhando de casa, a ErgoMax oferece suporte lombar ajustável, braços reguláveis em altura e um mecanismo de reclinação suave para manter o conforto durante o dia todo.",
    features: [
      "Apoio lombar com ajuste de altura",
      "Braços 3D ajustáveis",
      "Base giratória em nylon com rodízios silenciosos",
      "Encosto em tela respirável",
    ],
    dimensions: "0,64m (L) x 0,64m (P) x 1,10m–1,20m (A)",
    materials: "Tela mesh, estrutura em nylon reforçado",
    options: ["Preto", "Cinza"],
    image: "https://images.unsplash.com/photo-1676223303556-bef6fdac9331?w=1200&q=80&auto=format&fit=crop",
  },
  {
    id: "estante-oslo",
    name: "Estante Modular Oslo",
    category: "Estantes",
    price: 1290,
    shortDesc: "Módulos combináveis para livros, decoração e TV.",
    description:
      "A Oslo é uma solução modular pensada para quem gosta de organizar e exibir livros, objetos de decoração e o home theater em um único conjunto, com nichos abertos e fechados.",
    features: [
      "Nichos abertos e fechados combinados",
      "Suporta até 30kg por prateleira",
      "Furação para organização de cabos na parte traseira",
      "Montagem modular flexível",
    ],
    dimensions: "1,80m (L) x 0,35m (P) x 1,60m (A)",
    materials: "MDF com acabamento em laminado fosco",
    options: ["Nogueira", "Branco"],
    image: "https://images.unsplash.com/photo-1676223303556-bef6fdac9331?w=1200&q=80&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "estante-loft",
    name: "Estante Industrial Loft",
    category: "Estantes",
    price: 1590,
    shortDesc: "Estrutura em ferro preto com prateleiras em madeira maciça.",
    description:
      "Com inspiração industrial, a Loft combina estrutura em ferro preto fosco e prateleiras em madeira maciça, criando um visual despojado e ao mesmo tempo sofisticado.",
    features: [
      "5 prateleiras em madeira maciça",
      "Estrutura em ferro com pintura eletrostática",
      "Reforços diagonais para maior estabilidade",
      "Ideal para ambientes com pé-direito alto",
    ],
    dimensions: "1,20m (L) x 0,30m (P) x 1,90m (A)",
    materials: "Ferro e madeira maciça",
    options: ["Preto/Natural"],
    image: "https://images.unsplash.com/photo-1676223303556-bef6fdac9331?w=1200&q=80&auto=format&fit=crop",
  },
  {
    id: "rack-malta",
    name: "Rack Suspenso Malta",
    category: "Racks",
    price: 990,
    shortDesc: "Design suspenso com nicho para TVs de até 55 polegadas.",
    description:
      "O Rack Malta é fixado na parede, liberando o piso e criando uma sensação de amplitude no ambiente. Comporta TVs de até 55 polegadas e conta com compartimento fechado para organizar equipamentos.",
    features: [
      "Fixação suspensa (kit de instalação incluso)",
      "Compartimento fechado com porta basculante",
      "Suporta TVs de até 55 polegadas",
      "Acabamento fosco resistente a impressões digitais",
    ],
    dimensions: "1,60m (L) x 0,32m (P) x 0,38m (A)",
    materials: "MDF com acabamento em laminado fosco",
    options: ["Branco", "Nogueira"],
    image: "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&q=80&auto=format&fit=crop",
  },
  {
    id: "rack-sicilia",
    name: "Rack Painel Sicília",
    category: "Racks",
    price: 1150,
    shortDesc: "Conjunto rack + painel ripado para TV, com nichos decorativos.",
    description:
      "O conjunto Sicília combina rack baixo e painel ripado para TV, criando uma composição de destaque na sala. Os nichos assimétricos permitem exibir objetos de decoração e organizar equipamentos.",
    features: [
      "Painel ripado em madeira natural",
      "Nichos assimétricos abertos",
      "Rack com 2 portas e 1 gaveta",
      "Suporta TVs de até 60 polegadas",
    ],
    dimensions: "2,20m (L) x 1,80m (A do painel) x 0,40m (P do rack)",
    materials: "MDF laminado e ripas em madeira natural",
    options: ["Nogueira/Preto"],
    image: "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&q=80&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "armario-berlim",
    name: "Armário Multiuso Berlim",
    category: "Armários",
    price: 890,
    shortDesc: "Ideal para lavanderia, área de serviço ou escritório.",
    description:
      "Versátil e resistente, o Berlim é a solução para organizar lavanderias, áreas de serviço ou home offices. Prateleiras ajustáveis permitem adaptar o espaço interno conforme a necessidade.",
    features: [
      "4 portas com prateleiras ajustáveis internas",
      "Estrutura reforçada para suportar objetos pesados",
      "Pés niveladores para superfícies irregulares",
      "Acabamento resistente à umidade",
    ],
    dimensions: "1,60m (L) x 0,40m (P) x 1,80m (A)",
    materials: "MDP com revestimento hidrofugado",
    options: ["Branco"],
    image: "https://images.unsplash.com/photo-1718939045285-b67f9e9f9f8b?w=1200&q=80&auto=format&fit=crop",
  },
  {
    id: "armario-turim",
    name: "Armário de Cozinha Compacto Turim",
    category: "Armários",
    price: 1090,
    shortDesc: "Paneleiro com portas de vidro e prateleiras internas.",
    description:
      "Compacto e funcional, o Turim é pensado para cozinhas que precisam de espaço extra de armazenamento sem abrir mão do estilo, com portas de vidro que valorizam louças e utensílios.",
    features: [
      "2 portas de vidro temperado",
      "3 prateleiras internas ajustáveis",
      "Puxadores em metal escovado",
      "Base com rodapé de proteção contra umidade",
    ],
    dimensions: "0,90m (L) x 0,40m (P) x 1,85m (A)",
    materials: "MDF laminado e vidro temperado",
    options: ["Branco", "Cinza"],
    image: "https://images.unsplash.com/photo-1718939045285-b67f9e9f9f8b?w=1200&q=80&auto=format&fit=crop",
  },
];
